#!/bin/bash
# Script for installing Powerline systemwide
# For usage in vim, add the following line to .vimrc
#    set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/
# For more information, see:
# http://askubuntu.com/questions/283908/how-can-i-install-and-use-powerline-plugin

su -c 'pip install git+git://github.com/Lokaltog/powerline'

wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
sudo mv PowerlineSymbols.otf /usr/share/fonts/
sudo fc-cache -vf
sudo mv 10-powerline-symbols.conf /etc/fonts/conf.d/
